version: '3.9'

services:
  dotnet-packages:
    container_name: dotnet-packages
    environment:
      - ASPNETCORE_URLS=http://+
    volumes:
      - dotnet-packages-storage:/var/baget
    build:
      context: ./BaGet
    ports:
      - ${BAGET_HTTP_PORT}:80

# [ISSUE] sending logs to unexistisng service
# Don't understand how to disable that kind of behaviour
  docker-registry:
    container_name: docker-registry
    volumes:
      - docker-registry-storage:/var/lib/registry
    build:
      context: ./DockerRegistry
    ports:
      - ${DOCKER_REGISTRY_HTTP_PORT}:5000

volumes:
  dotnet-packages-storage:
    name: dotnet-packages-storage
  docker-registry-storage:
    name: docker-registry-storage